### ISSUE TITLE
Working?

### ISSUE THREAD

**Issue by dovy** [apengwin/py_node#2]

**Comment by dovy** [comment]
I get the following error:

```
Error:  { ApiError: Forbidden
                                                                      at Object.parseHttpRespMessage (/user_code/node_modules/@google-cloud/storage/node_modules/@google-cloud/common/src/util.js:156:33)
                                                                      at Object.handleResp (/user_code/node_modules/@google-cloud/storage/node_modules/@google-cloud/common/src/util.js:131:18)
                                                                      at Duplexify.<anonymous> (/user_code/node_modules/@google-cloud/storage/src/file.js:724:21)
                                                                      at emitOne (events.js:96:13)
                                                                      at Duplexify.emit (events.js:188:7)
                                                                      at emitOne (events.js:96:13)
                                                                      at DestroyableTransform.emit (events.js:188:7)
                                                                      at emitOne (events.js:96:13)
                                                                      at Request.emit (events.js:188:7)
                                                                      at Request.<anonymous> (/user_code/node_modules/@google-cloud/storage/node_modules/request/request.js:1108:14)
                                                                    code: 403,
```

Is there some additional setup somewhere?

**Comment by apengwin** [comment]
@dovy  this was just some code that i threw together to prototype something. There's a bunch of auth and setting up gcloud buckets involved.
